# name: "Test Code Review"

# on:
#   pull_request:
#     paths-ignore:
#       - "*.md"
#       - "LICENSE"

# jobs:
#   review:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write
#     steps:
#       - uses: actions/checkout@v3
#       - name: "Get diff of the pull request"
#         id: get_diff
#         shell: bash
#         env:
#           PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
#         run: |-
#           git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}:${{ env.PULL_REQUEST_HEAD_REF }}"
#           git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
#           git diff "origin/${{ env.PULL_REQUEST_HEAD_REF }}" > "diff.txt"
#           # shellcheck disable=SC2086
#           echo "diff=$(cat "diff.txt")" >> $GITHUB_ENV
#       - uses: yu-iskw/gpt-code-review-action@v0.3.0
#         name: "Code Review by GPT"
#         id: review
#         with:
#           openai_api_key: ${{ secrets.OPENAI_API_KEY }}
#           github_token: ${{ vars.GITHUBB_TOKEN }}
#           github_repository: ${{ github.repository }}
#           github_pull_request_number: ${{ github.event.pull_request.number }}
#           git_commit_hash: ${{ github.event.pull_request.head.sha }}
#           model: "gpt-3.5-turbo"
#           temperature: "0.1"
#           max_tokens: "512"
#           top_p: "1"
#           frequency_penalty: "0.0"
#           presence_penalty: "0.0"
#           pull_request_diff: |-
#             ${{ steps.get_diff.outputs.pull_request_diff }}
#           pull_request_chunk_size: "3500"
#           extra_prompt: |-
#             You are very familiar with python too.
#           log_level: "DEBUG"












# name: Code Review GPT

# on:
#   pull_request:
#     branches: [master]

# jobs:
#   run_code_review:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
              
#       - name: Commit-crtiq        
#         uses: cAPRIcaT3/apprentice_stable@code-commit


      # - name: Code Review GPT
      #   uses: mattzcarey/code-review-gpt@v0.1.4-alpha
      #   with:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     GITHUB_TOKEN: ${{ vars.GITHUBB_TOKEN }}
      #     MODEL: 'gpt-3.5-turbo'

# name: "Test Code Review"

# on:
#   pull_request:
#     paths-ignore:
#       - "*.md"
#       - "LICENSE"

# jobs:
#   review:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write
#     steps:
#       - uses: actions/checkout@v3
#       - name: "Get diff of the pull request"
#         id: get_diff
#         shell: bash
#         env:
#           PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
#         run: |-
#           git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}:${{ env.PULL_REQUEST_HEAD_REF }}"
#           git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
#           git diff "origin/${{ env.PULL_REQUEST_HEAD_REF }}" > "diff.txt"
#           # shellcheck disable=SC2086
#           echo "diff=$(cat "diff.txt")" >> $GITHUB_ENV
#       - uses: yu-iskw/gpt-code-review-action@v0.3.0
#         name: "Code Review by GPT"
#         id: review
#         with:
#           openai_api_key: ${{ secrets.OPENAI_API_KEY }}
#           github_token: ${{ vars.GITHUBB_TOKEN }}
#           github_repository: ${{ github.repository }}
#           github_pull_request_number: ${{ github.event.pull_request.number }}
#           git_commit_hash: ${{ github.event.pull_request.head.sha }}
#           model: "gpt-3.5-turbo"
#           temperature: "0.1"
#           max_tokens: "512"
#           top_p: "1"
#           frequency_penalty: "0.0"
#           presence_penalty: "0.0"
#           pull_request_diff: |-
#             ${{ steps.get_diff.outputs.pull_request_diff }}
#           pull_request_chunk_size: "3500"
#           extra_prompt: |-
#             You are very familiar with python too.
#           log_level: "DEBUG"












name: Code Review GPT

on:
  pull_request:
    branches: [master]

# jobs:
#   run_code_review:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
              
#       - name: Commit-crtiq        
#         uses: cAPRIcaT3/apprentice_stable@code-commit


      # - name: Code Review GPT
      #   uses: mattzcarey/code-review-gpt@v0.1.4-alpha
      #   with:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     GITHUB_TOKEN: ${{ vars.GITHUBB_TOKEN }}
      #     MODEL: 'gpt-3.5-turbo'

jobs:        
  Review:
    runs-on: ubuntu-latest
    container: mayankaz104/code-review-llmas:1.0.2
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: removing dubious ownership
        shell: bash
        run: git config --global safe.directory '*'
      - name: print-diff
        shell: bash
        run: |
          git fetch origin master
          git diff origin/master..HEAD > difference_hunk.txt
          find . -type f -name difference_hunk.txt
          pwd
          echo "difference hunk = "
          cat difference_hunk.txt
          
      # - name: Cache dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ env.HOME }}/.cache/pip
      #     key: ${{ runner.os }}-dependencies-${{ hashFiles('requirements.txt') }}-{{ fileset.modifiedTime('requirements.txt') }}
      # - uses: actions/setup-python@v4
      #   with:
      #       python-version: '3.10' 
      # - name: installations
      #   run: |
      #     pip install --upgrade pip
      #     pip install -r requirements.txt
      - name: Run Python script
        run: python /app/src/commenter.py
      - name: Read PR comment from file
        run: cat /app/src/files/output.txt > pr_comment.txt
      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: pr_comment.txt
          repo-directory: '/app/'
          requirements-path: 'requirements.txt'
